curl -o chiang-mai-thailand.jpg https://nomadlist.com/assets/cities/500px/chiang-mai-thailand.jpg
curl -o novi-sad-serbia.jpg https://nomadlist.com/assets/cities/500px/novi-sad-serbia.jpg
curl -o varna-bulgaria.jpg https://nomadlist.com/assets/cities/500px/varna-bulgaria.jpg
curl -o belgrade-serbia.jpg https://nomadlist.com/assets/cities/500px/belgrade-serbia.jpg
curl -o braga-portugal.jpg https://nomadlist.com/assets/cities/500px/braga-portugal.jpg
curl -o bangkok-thailand.jpg https://nomadlist.com/assets/cities/500px/bangkok-thailand.jpg
curl -o odesa-ukraine.jpg https://nomadlist.com/assets/cities/500px/odesa-ukraine.jpg
curl -o tbilisi-georgia.jpg https://nomadlist.com/assets/cities/500px/tbilisi-georgia.jpg
curl -o kota-kinabalu-malaysia.jpg https://nomadlist.com/assets/cities/500px/kota-kinabalu-malaysia.jpg
curl -o kingston-jamaica.jpg https://nomadlist.com/assets/cities/500px/kingston-jamaica.jpg
curl -o tijuana-mexico.jpg https://nomadlist.com/assets/cities/500px/tijuana-mexico.jpg
curl -o osijek-croatia.jpg https://nomadlist.com/assets/cities/500px/osijek-croatia.jpg
curl -o taichung-taiwan.jpg https://nomadlist.com/assets/cities/500px/taichung-taiwan.jpg
curl -o budapest-hungary.jpg https://nomadlist.com/assets/cities/500px/budapest-hungary.jpg
curl -o addis-ababa-ethiopia.jpg https://nomadlist.com/assets/cities/500px/addis-ababa-ethiopia.jpg
curl -o navi-mumbai-india.jpg https://nomadlist.com/assets/cities/500px/navi-mumbai-india.jpg
curl -o lviv-ukraine.jpg https://nomadlist.com/assets/cities/500px/lviv-ukraine.jpg
curl -o taghazout-morocco.jpg https://nomadlist.com/assets/cities/500px/taghazout-morocco.jpg
curl -o las-vegas-nv-united-states.jpg https://nomadlist.com/assets/cities/500px/las-vegas-nv-united-states.jpg
curl -o split-croatia.jpg https://nomadlist.com/assets/cities/500px/split-croatia.jpg
curl -o sofia-bulgaria.jpg https://nomadlist.com/assets/cities/500px/sofia-bulgaria.jpg
curl -o bishkek-kyrgyzstan.jpg https://nomadlist.com/assets/cities/500px/bishkek-kyrgyzstan.jpg
curl -o chattanooga-tn-united-states.jpg https://nomadlist.com/assets/cities/500px/chattanooga-tn-united-states.jpg
curl -o kampala-uganda.jpg https://nomadlist.com/assets/cities/500px/kampala-uganda.jpg
curl -o porto-portugal.jpg https://nomadlist.com/assets/cities/500px/porto-portugal.jpg
curl -o riyadh-saudi-arabia.jpg https://nomadlist.com/assets/cities/500px/riyadh-saudi-arabia.jpg
curl -o las-palmas-canary-islands-spain.jpg https://nomadlist.com/assets/cities/500px/las-palmas-canary-islands-spain.jpg
curl -o davao-philippines.jpg https://nomadlist.com/assets/cities/500px/davao-philippines.jpg
curl -o hermosillo-mexico.jpg https://nomadlist.com/assets/cities/500px/hermosillo-mexico.jpg
curl -o knoxville-tn-united-states.jpg https://nomadlist.com/assets/cities/500px/knoxville-tn-united-states.jpg
curl -o merida-mexico.jpg https://nomadlist.com/assets/cities/500px/merida-mexico.jpg
curl -o natal-brazil.jpg https://nomadlist.com/assets/cities/500px/natal-brazil.jpg
curl -o kuala-lumpur-malaysia.jpg https://nomadlist.com/assets/cities/500px/kuala-lumpur-malaysia.jpg
curl -o thessaloniki-greece.jpg https://nomadlist.com/assets/cities/500px/thessaloniki-greece.jpg
curl -o yerevan-armenia.jpg https://nomadlist.com/assets/cities/500px/yerevan-armenia.jpg
curl -o monterrey-mexico.jpg https://nomadlist.com/assets/cities/500px/monterrey-mexico.jpg
curl -o plovdiv-bulgaria.jpg https://nomadlist.com/assets/cities/500px/plovdiv-bulgaria.jpg
curl -o tartu-estonia.jpg https://nomadlist.com/assets/cities/500px/tartu-estonia.jpg
curl -o rijeka-croatia.jpg https://nomadlist.com/assets/cities/500px/rijeka-croatia.jpg
curl -o minsk-belarus.jpg https://nomadlist.com/assets/cities/500px/minsk-belarus.jpg
curl -o sarajevo-bosnia-herzegovina.jpg https://nomadlist.com/assets/cities/500px/sarajevo-bosnia-herzegovina.jpg
curl -o canggu-bali-indonesia.jpg https://nomadlist.com/assets/cities/500px/canggu-bali-indonesia.jpg
curl -o oaxaca-mexico.jpg https://nomadlist.com/assets/cities/500px/oaxaca-mexico.jpg
curl -o surabaya-indonesia.jpg https://nomadlist.com/assets/cities/500px/surabaya-indonesia.jpg
curl -o windsor-canada.jpg https://nomadlist.com/assets/cities/500px/windsor-canada.jpg
curl -o zadar-croatia.jpg https://nomadlist.com/assets/cities/500px/zadar-croatia.jpg
curl -o lahore-pakistan.jpg https://nomadlist.com/assets/cities/500px/lahore-pakistan.jpg
curl -o jarabacoa-dominican-republic.jpg https://nomadlist.com/assets/cities/500px/jarabacoa-dominican-republic.jpg
curl -o banja-luka-bosnia-herzegovina.jpg https://nomadlist.com/assets/cities/500px/banja-luka-bosnia-herzegovina.jpg
curl -o new-delhi-india.jpg https://nomadlist.com/assets/cities/500px/new-delhi-india.jpg
curl -o arequipa-peru.jpg https://nomadlist.com/assets/cities/500px/arequipa-peru.jpg
curl -o funchal-portugal.jpg https://nomadlist.com/assets/cities/500px/funchal-portugal.jpg
curl -o dallas-tx-united-states.jpg https://nomadlist.com/assets/cities/500px/dallas-tx-united-states.jpg
curl -o aveiro-portugal.jpg https://nomadlist.com/assets/cities/500px/aveiro-portugal.jpg
curl -o tashkent-uzbekistan.jpg https://nomadlist.com/assets/cities/500px/tashkent-uzbekistan.jpg
curl -o yangon-myanmar.jpg https://nomadlist.com/assets/cities/500px/yangon-myanmar.jpg
curl -o nantes-france.jpg https://nomadlist.com/assets/cities/500px/nantes-france.jpg
curl -o phuket-thailand.jpg https://nomadlist.com/assets/cities/500px/phuket-thailand.jpg
curl -o ivano-frankivsk-ukraine.jpg https://nomadlist.com/assets/cities/500px/ivano-frankivsk-ukraine.jpg
curl -o jakarta-indonesia.jpg https://nomadlist.com/assets/cities/500px/jakarta-indonesia.jpg
curl -o kaohsiung-taiwan.jpg https://nomadlist.com/assets/cities/500px/kaohsiung-taiwan.jpg
curl -o da-lat-vietnam.jpg https://nomadlist.com/assets/cities/500px/da-lat-vietnam.jpg
curl -o oulu-finland.jpg https://nomadlist.com/assets/cities/500px/oulu-finland.jpg
curl -o lisbon-portugal.jpg https://nomadlist.com/assets/cities/500px/lisbon-portugal.jpg
curl -o malaga-spain.jpg https://nomadlist.com/assets/cities/500px/malaga-spain.jpg
curl -o ho-chi-minh-city-vietnam.jpg https://nomadlist.com/assets/cities/500px/ho-chi-minh-city-vietnam.jpg
curl -o port-elizabeth-south-africa.jpg https://nomadlist.com/assets/cities/500px/port-elizabeth-south-africa.jpg
curl -o rochester-ny-united-states.jpg https://nomadlist.com/assets/cities/500px/rochester-ny-united-states.jpg
curl -o karlsruhe-germany.jpg https://nomadlist.com/assets/cities/500px/karlsruhe-germany.jpg
curl -o kharkiv-ukraine.jpg https://nomadlist.com/assets/cities/500px/kharkiv-ukraine.jpg
curl -o coimbra-portugal.jpg https://nomadlist.com/assets/cities/500px/coimbra-portugal.jpg
curl -o cochabamba-bolivia.jpg https://nomadlist.com/assets/cities/500px/cochabamba-bolivia.jpg
curl -o kiev-ukraine.jpg https://nomadlist.com/assets/cities/500px/kiev-ukraine.jpg
curl -o phnom-penh-cambodia.jpg https://nomadlist.com/assets/cities/500px/phnom-penh-cambodia.jpg
curl -o memphis-tn-united-states.jpg https://nomadlist.com/assets/cities/500px/memphis-tn-united-states.jpg
curl -o jeju-island-south-korea.jpg https://nomadlist.com/assets/cities/500px/jeju-island-south-korea.jpg
curl -o lublin-poland.jpg https://nomadlist.com/assets/cities/500px/lublin-poland.jpg
curl -o cordoba-argentina.jpg https://nomadlist.com/assets/cities/500px/cordoba-argentina.jpg
curl -o medellin-colombia.jpg https://nomadlist.com/assets/cities/500px/medellin-colombia.jpg
curl -o provo-ut-united-states.jpg https://nomadlist.com/assets/cities/500px/provo-ut-united-states.jpg
curl -o aalborg-denmark.jpg https://nomadlist.com/assets/cities/500px/aalborg-denmark.jpg
curl -o puerto-vallarta-mexico.jpg https://nomadlist.com/assets/cities/500px/puerto-vallarta-mexico.jpg
curl -o nuremberg-germany.jpg https://nomadlist.com/assets/cities/500px/nuremberg-germany.jpg
curl -o orlando-fl-united-states.jpg https://nomadlist.com/assets/cities/500px/orlando-fl-united-states.jpg
curl -o sharjah-united-arab-emirates.jpg https://nomadlist.com/assets/cities/500px/sharjah-united-arab-emirates.jpg
curl -o queretaro-mexico.jpg https://nomadlist.com/assets/cities/500px/queretaro-mexico.jpg
curl -o austin-tx-united-states.jpg https://nomadlist.com/assets/cities/500px/austin-tx-united-states.jpg
curl -o bologna-italy.jpg https://nomadlist.com/assets/cities/500px/bologna-italy.jpg
curl -o ploiesti-romania.jpg https://nomadlist.com/assets/cities/500px/ploiesti-romania.jpg
curl -o krivoy-rog-ukraine.jpg https://nomadlist.com/assets/cities/500px/krivoy-rog-ukraine.jpg
curl -o valencia-spain.jpg https://nomadlist.com/assets/cities/500px/valencia-spain.jpg
curl -o brno-czech-republic.jpg https://nomadlist.com/assets/cities/500px/brno-czech-republic.jpg
curl -o zagreb-croatia.jpg https://nomadlist.com/assets/cities/500px/zagreb-croatia.jpg
curl -o lagos-nigeria.jpg https://nomadlist.com/assets/cities/500px/lagos-nigeria.jpg
curl -o prague-czech-republic.jpg https://nomadlist.com/assets/cities/500px/prague-czech-republic.jpg
curl -o leipzig-germany.jpg https://nomadlist.com/assets/cities/500px/leipzig-germany.jpg
curl -o osaka-japan.jpg https://nomadlist.com/assets/cities/500px/osaka-japan.jpg
curl -o chatham-canada.jpg https://nomadlist.com/assets/cities/500px/chatham-canada.jpg
curl -o antigua-guatemala.jpg https://nomadlist.com/assets/cities/500px/antigua-guatemala.jpg
curl -o toulouse-france.jpg https://nomadlist.com/assets/cities/500px/toulouse-france.jpg
curl -o nairobi-kenya.jpg https://nomadlist.com/assets/cities/500px/nairobi-kenya.jpg
curl -o miami-fl-united-states.jpg https://nomadlist.com/assets/cities/500px/miami-fl-united-states.jpg
curl -o west-palm-beach-fl-united-states.jpg https://nomadlist.com/assets/cities/500px/west-palm-beach-fl-united-states.jpg
curl -o palawan-philippines.jpg https://nomadlist.com/assets/cities/500px/palawan-philippines.jpg
curl -o the-hague-netherlands.jpg https://nomadlist.com/assets/cities/500px/the-hague-netherlands.jpg
curl -o tucson-az-united-states.jpg https://nomadlist.com/assets/cities/500px/tucson-az-united-states.jpg
curl -o kigali-rwanda.jpg https://nomadlist.com/assets/cities/500px/kigali-rwanda.jpg
curl -o buenos-aires-argentina.jpg https://nomadlist.com/assets/cities/500px/buenos-aires-argentina.jpg
curl -o ubud-bali-indonesia.jpg https://nomadlist.com/assets/cities/500px/ubud-bali-indonesia.jpg
curl -o riga-latvia.jpg https://nomadlist.com/assets/cities/500px/riga-latvia.jpg
curl -o nashville-tn-united-states.jpg https://nomadlist.com/assets/cities/500px/nashville-tn-united-states.jpg
curl -o st-louis-mo-united-states.jpg https://nomadlist.com/assets/cities/500px/st-louis-mo-united-states.jpg
curl -o rethymno-greece.jpg https://nomadlist.com/assets/cities/500px/rethymno-greece.jpg
curl -o tirana-albania.jpg https://nomadlist.com/assets/cities/500px/tirana-albania.jpg
curl -o panama-city-panama.jpg https://nomadlist.com/assets/cities/500px/panama-city-panama.jpg
curl -o casablanca-morocco.jpg https://nomadlist.com/assets/cities/500px/casablanca-morocco.jpg
curl -o adelaide-australia.jpg https://nomadlist.com/assets/cities/500px/adelaide-australia.jpg
curl -o victoria-canada.jpg https://nomadlist.com/assets/cities/500px/victoria-canada.jpg
curl -o constanta-romania.jpg https://nomadlist.com/assets/cities/500px/constanta-romania.jpg
curl -o nis-solomon-islands.jpg https://nomadlist.com/assets/cities/500px/nis-solomon-islands.jpg
curl -o cali-colombia.jpg https://nomadlist.com/assets/cities/500px/cali-colombia.jpg
curl -o iasi-romania.jpg https://nomadlist.com/assets/cities/500px/iasi-romania.jpg
curl -o ulaanbaatar-mongolia.jpg https://nomadlist.com/assets/cities/500px/ulaanbaatar-mongolia.jpg
curl -o bratislava-slovakia.jpg https://nomadlist.com/assets/cities/500px/bratislava-slovakia.jpg
curl -o avellino-italy.jpg https://nomadlist.com/assets/cities/500px/avellino-italy.jpg
curl -o tampere-finland.jpg https://nomadlist.com/assets/cities/500px/tampere-finland.jpg
curl -o brasilia-brazil.jpg https://nomadlist.com/assets/cities/500px/brasilia-brazil.jpg
curl -o chisinau-moldova.jpg https://nomadlist.com/assets/cities/500px/chisinau-moldova.jpg
curl -o jaipur-india.jpg https://nomadlist.com/assets/cities/500px/jaipur-india.jpg
curl -o pai-thailand.jpg https://nomadlist.com/assets/cities/500px/pai-thailand.jpg
curl -o patras-greece.jpg https://nomadlist.com/assets/cities/500px/patras-greece.jpg
curl -o vientiane-laos.jpg https://nomadlist.com/assets/cities/500px/vientiane-laos.jpg
curl -o siem-reap-cambodia.jpg https://nomadlist.com/assets/cities/500px/siem-reap-cambodia.jpg
curl -o ko-samui-thailand.jpg https://nomadlist.com/assets/cities/500px/ko-samui-thailand.jpg
curl -o penang-malaysia.jpg https://nomadlist.com/assets/cities/500px/penang-malaysia.jpg
curl -o cluj-romania.jpg https://nomadlist.com/assets/cities/500px/cluj-romania.jpg
curl -o seoul-south-korea.jpg https://nomadlist.com/assets/cities/500px/seoul-south-korea.jpg
curl -o la-plata-argentina.jpg https://nomadlist.com/assets/cities/500px/la-plata-argentina.jpg
curl -o santo-domingo-dominican-republic.jpg https://nomadlist.com/assets/cities/500px/santo-domingo-dominican-republic.jpg
curl -o caracas-venezuela.jpg https://nomadlist.com/assets/cities/500px/caracas-venezuela.jpg
curl -o saint-petersburg-russia.jpg https://nomadlist.com/assets/cities/500px/saint-petersburg-russia.jpg
curl -o johor-bahru-malaysia.jpg https://nomadlist.com/assets/cities/500px/johor-bahru-malaysia.jpg
curl -o bilbao-spain.jpg https://nomadlist.com/assets/cities/500px/bilbao-spain.jpg
curl -o timisoara-romania.jpg https://nomadlist.com/assets/cities/500px/timisoara-romania.jpg
curl -o charleston-sc-united-states.jpg https://nomadlist.com/assets/cities/500px/charleston-sc-united-states.jpg
curl -o poznan-poland.jpg https://nomadlist.com/assets/cities/500px/poznan-poland.jpg
curl -o bandung-indonesia.jpg https://nomadlist.com/assets/cities/500px/bandung-indonesia.jpg
curl -o quebec-city-canada.jpg https://nomadlist.com/assets/cities/500px/quebec-city-canada.jpg
curl -o gdansk-poland.jpg https://nomadlist.com/assets/cities/500px/gdansk-poland.jpg
curl -o louisville-ky-united-states.jpg https://nomadlist.com/assets/cities/500px/louisville-ky-united-states.jpg
curl -o jena-germany.jpg https://nomadlist.com/assets/cities/500px/jena-germany.jpg
curl -o surat-india.jpg https://nomadlist.com/assets/cities/500px/surat-india.jpg
curl -o lima-peru.jpg https://nomadlist.com/assets/cities/500px/lima-peru.jpg
curl -o puerto-viejo-costa-rica.jpg https://nomadlist.com/assets/cities/500px/puerto-viejo-costa-rica.jpg
curl -o brasov-romania.jpg https://nomadlist.com/assets/cities/500px/brasov-romania.jpg
curl -o curitiba-brazil.jpg https://nomadlist.com/assets/cities/500px/curitiba-brazil.jpg
curl -o cairo-egypt.jpg https://nomadlist.com/assets/cities/500px/cairo-egypt.jpg
curl -o ottawa-canada.jpg https://nomadlist.com/assets/cities/500px/ottawa-canada.jpg
curl -o berlin-germany.jpg https://nomadlist.com/assets/cities/500px/berlin-germany.jpg
curl -o singapore-singapore.jpg https://nomadlist.com/assets/cities/500px/singapore-singapore.jpg
curl -o obninsk-russia.jpg https://nomadlist.com/assets/cities/500px/obninsk-russia.jpg
curl -o santa-cruz-bolivia.jpg https://nomadlist.com/assets/cities/500px/santa-cruz-bolivia.jpg
curl -o lille-france.jpg https://nomadlist.com/assets/cities/500px/lille-france.jpg
curl -o chachapoyas-peru.jpg https://nomadlist.com/assets/cities/500px/chachapoyas-peru.jpg
curl -o genoa-italy.jpg https://nomadlist.com/assets/cities/500px/genoa-italy.jpg
curl -o hanoi-vietnam.jpg https://nomadlist.com/assets/cities/500px/hanoi-vietnam.jpg
curl -o thane-india.jpg https://nomadlist.com/assets/cities/500px/thane-india.jpg
curl -o katowice-poland.jpg https://nomadlist.com/assets/cities/500px/katowice-poland.jpg
curl -o edmonton-canada.jpg https://nomadlist.com/assets/cities/500px/edmonton-canada.jpg
curl -o guangzhou-china.jpg https://nomadlist.com/assets/cities/500px/guangzhou-china.jpg
curl -o san-miguel-de-allende-mexico.jpg https://nomadlist.com/assets/cities/500px/san-miguel-de-allende-mexico.jpg
curl -o kansas-city-mo-united-states.jpg https://nomadlist.com/assets/cities/500px/kansas-city-mo-united-states.jpg
curl -o bangalore-india.jpg https://nomadlist.com/assets/cities/500px/bangalore-india.jpg
curl -o belo-horizonte-brazil.jpg https://nomadlist.com/assets/cities/500px/belo-horizonte-brazil.jpg
curl -o ljubljana-slovenia.jpg https://nomadlist.com/assets/cities/500px/ljubljana-slovenia.jpg
curl -o ludhiana-india.jpg https://nomadlist.com/assets/cities/500px/ludhiana-india.jpg
curl -o santiago-chile.jpg https://nomadlist.com/assets/cities/500px/santiago-chile.jpg
curl -o shenzhen-china.jpg https://nomadlist.com/assets/cities/500px/shenzhen-china.jpg
curl -o fort-lauderdale-fl-united-states.jpg https://nomadlist.com/assets/cities/500px/fort-lauderdale-fl-united-states.jpg
curl -o mexico-city-mexico.jpg https://nomadlist.com/assets/cities/500px/mexico-city-mexico.jpg
curl -o frankfurt-germany.jpg https://nomadlist.com/assets/cities/500px/frankfurt-germany.jpg
curl -o halifax-canada.jpg https://nomadlist.com/assets/cities/500px/halifax-canada.jpg
curl -o caye-caulker-belize.jpg https://nomadlist.com/assets/cities/500px/caye-caulker-belize.jpg
curl -o noida-india.jpg https://nomadlist.com/assets/cities/500px/noida-india.jpg
curl -o liverpool-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/liverpool-united-kingdom.jpg
curl -o colombo-sri-lanka.jpg https://nomadlist.com/assets/cities/500px/colombo-sri-lanka.jpg
curl -o bogota-colombia.jpg https://nomadlist.com/assets/cities/500px/bogota-colombia.jpg
curl -o chico-ca-united-states.jpg https://nomadlist.com/assets/cities/500px/chico-ca-united-states.jpg
curl -o porto-alegre-brazil.jpg https://nomadlist.com/assets/cities/500px/porto-alegre-brazil.jpg
curl -o perth-australia.jpg https://nomadlist.com/assets/cities/500px/perth-australia.jpg
curl -o marseille-france.jpg https://nomadlist.com/assets/cities/500px/marseille-france.jpg
curl -o utrecht-netherlands.jpg https://nomadlist.com/assets/cities/500px/utrecht-netherlands.jpg
curl -o bucharest-romania.jpg https://nomadlist.com/assets/cities/500px/bucharest-romania.jpg
curl -o khartoum-sudan.jpg https://nomadlist.com/assets/cities/500px/khartoum-sudan.jpg
curl -o krasnodar-russia.jpg https://nomadlist.com/assets/cities/500px/krasnodar-russia.jpg
curl -o gent-belgium.jpg https://nomadlist.com/assets/cities/500px/gent-belgium.jpg
curl -o hyderabad-india.jpg https://nomadlist.com/assets/cities/500px/hyderabad-india.jpg
curl -o bremen-germany.jpg https://nomadlist.com/assets/cities/500px/bremen-germany.jpg
curl -o krakow-poland.jpg https://nomadlist.com/assets/cities/500px/krakow-poland.jpg
curl -o cebu-philippines.jpg https://nomadlist.com/assets/cities/500px/cebu-philippines.jpg
curl -o szczecin-poland.jpg https://nomadlist.com/assets/cities/500px/szczecin-poland.jpg
curl -o madrid-spain.jpg https://nomadlist.com/assets/cities/500px/madrid-spain.jpg
curl -o sydney-australia.jpg https://nomadlist.com/assets/cities/500px/sydney-australia.jpg
curl -o madison-wi-united-states.jpg https://nomadlist.com/assets/cities/500px/madison-wi-united-states.jpg
curl -o detroit-mi-united-states.jpg https://nomadlist.com/assets/cities/500px/detroit-mi-united-states.jpg
curl -o nagpur-india.jpg https://nomadlist.com/assets/cities/500px/nagpur-india.jpg
curl -o toronto-canada.jpg https://nomadlist.com/assets/cities/500px/toronto-canada.jpg
curl -o montreal-canada.jpg https://nomadlist.com/assets/cities/500px/montreal-canada.jpg
curl -o sao-paulo-brazil.jpg https://nomadlist.com/assets/cities/500px/sao-paulo-brazil.jpg
curl -o indianapolis-in-united-states.jpg https://nomadlist.com/assets/cities/500px/indianapolis-in-united-states.jpg
curl -o muscat-oman.jpg https://nomadlist.com/assets/cities/500px/muscat-oman.jpg
curl -o windhoek-namibia.jpg https://nomadlist.com/assets/cities/500px/windhoek-namibia.jpg
curl -o mississauga-canada.jpg https://nomadlist.com/assets/cities/500px/mississauga-canada.jpg
curl -o san-salvador-el-salvador.jpg https://nomadlist.com/assets/cities/500px/san-salvador-el-salvador.jpg
curl -o fargo-nd-united-states.jpg https://nomadlist.com/assets/cities/500px/fargo-nd-united-states.jpg
curl -o dresden-germany.jpg https://nomadlist.com/assets/cities/500px/dresden-germany.jpg
curl -o pretoria-south-africa.jpg https://nomadlist.com/assets/cities/500px/pretoria-south-africa.jpg
curl -o dakar-senegal.jpg https://nomadlist.com/assets/cities/500px/dakar-senegal.jpg
curl -o tallinn-estonia.jpg https://nomadlist.com/assets/cities/500px/tallinn-estonia.jpg
curl -o cancun-mexico.jpg https://nomadlist.com/assets/cities/500px/cancun-mexico.jpg
curl -o stuttgart-germany.jpg https://nomadlist.com/assets/cities/500px/stuttgart-germany.jpg
curl -o buffalo-ny-united-states.jpg https://nomadlist.com/assets/cities/500px/buffalo-ny-united-states.jpg
curl -o granada-spain.jpg https://nomadlist.com/assets/cities/500px/granada-spain.jpg
curl -o new-orleans-la-united-states.jpg https://nomadlist.com/assets/cities/500px/new-orleans-la-united-states.jpg
curl -o hoi-an-vietnam.jpg https://nomadlist.com/assets/cities/500px/hoi-an-vietnam.jpg
curl -o nasik-india.jpg https://nomadlist.com/assets/cities/500px/nasik-india.jpg
curl -o manila-philippines.jpg https://nomadlist.com/assets/cities/500px/manila-philippines.jpg
curl -o oakland-ca-united-states.jpg https://nomadlist.com/assets/cities/500px/oakland-ca-united-states.jpg
curl -o ibi-spain.jpg https://nomadlist.com/assets/cities/500px/ibi-spain.jpg
curl -o san-diego-ca-united-states.jpg https://nomadlist.com/assets/cities/500px/san-diego-ca-united-states.jpg
curl -o atlanta-ga-united-states.jpg https://nomadlist.com/assets/cities/500px/atlanta-ga-united-states.jpg
curl -o taipei-taiwan.jpg https://nomadlist.com/assets/cities/500px/taipei-taiwan.jpg
curl -o pune-india.jpg https://nomadlist.com/assets/cities/500px/pune-india.jpg
curl -o winnipeg-canada.jpg https://nomadlist.com/assets/cities/500px/winnipeg-canada.jpg
curl -o craiova-romania.jpg https://nomadlist.com/assets/cities/500px/craiova-romania.jpg
curl -o florianopolis-brazil.jpg https://nomadlist.com/assets/cities/500px/florianopolis-brazil.jpg
curl -o recife-brazil.jpg https://nomadlist.com/assets/cities/500px/recife-brazil.jpg
curl -o chennai-india.jpg https://nomadlist.com/assets/cities/500px/chennai-india.jpg
curl -o guatemala-city-guatemala.jpg https://nomadlist.com/assets/cities/500px/guatemala-city-guatemala.jpg
curl -o a-coruna-spain.jpg https://nomadlist.com/assets/cities/500px/a-coruna-spain.jpg
curl -o saratov-russia.jpg https://nomadlist.com/assets/cities/500px/saratov-russia.jpg
curl -o athens-greece.jpg https://nomadlist.com/assets/cities/500px/athens-greece.jpg
curl -o hamburg-germany.jpg https://nomadlist.com/assets/cities/500px/hamburg-germany.jpg
curl -o podgorica-montenegro.jpg https://nomadlist.com/assets/cities/500px/podgorica-montenegro.jpg
curl -o vadodara-india.jpg https://nomadlist.com/assets/cities/500px/vadodara-india.jpg
curl -o vienna-austria.jpg https://nomadlist.com/assets/cities/500px/vienna-austria.jpg
curl -o cologne-germany.jpg https://nomadlist.com/assets/cities/500px/cologne-germany.jpg
curl -o montevideo-uruguay.jpg https://nomadlist.com/assets/cities/500px/montevideo-uruguay.jpg
curl -o asheville-nc-united-states.jpg https://nomadlist.com/assets/cities/500px/asheville-nc-united-states.jpg
curl -o beacon-ny-united-states.jpg https://nomadlist.com/assets/cities/500px/beacon-ny-united-states.jpg
curl -o kowloon-hong-kong.jpg https://nomadlist.com/assets/cities/500px/kowloon-hong-kong.jpg
curl -o maputo-mozambique.jpg https://nomadlist.com/assets/cities/500px/maputo-mozambique.jpg
curl -o tunis-tunisia.jpg https://nomadlist.com/assets/cities/500px/tunis-tunisia.jpg
curl -o cartagena-colombia.jpg https://nomadlist.com/assets/cities/500px/cartagena-colombia.jpg
curl -o ramallah-palestine.jpg https://nomadlist.com/assets/cities/500px/ramallah-palestine.jpg
curl -o bar-montenegro.jpg https://nomadlist.com/assets/cities/500px/bar-montenegro.jpg
curl -o durban-south-africa.jpg https://nomadlist.com/assets/cities/500px/durban-south-africa.jpg
curl -o agadir-morocco.jpg https://nomadlist.com/assets/cities/500px/agadir-morocco.jpg
curl -o amman-jordan.jpg https://nomadlist.com/assets/cities/500px/amman-jordan.jpg
curl -o baltimore-md-united-states.jpg https://nomadlist.com/assets/cities/500px/baltimore-md-united-states.jpg
curl -o tehran-iran.jpg https://nomadlist.com/assets/cities/500px/tehran-iran.jpg
curl -o florence-italy.jpg https://nomadlist.com/assets/cities/500px/florence-italy.jpg
curl -o fortaleza-brazil.jpg https://nomadlist.com/assets/cities/500px/fortaleza-brazil.jpg
curl -o mumbai-india.jpg https://nomadlist.com/assets/cities/500px/mumbai-india.jpg
curl -o hobart-australia.jpg https://nomadlist.com/assets/cities/500px/hobart-australia.jpg
curl -o moncton-canada.jpg https://nomadlist.com/assets/cities/500px/moncton-canada.jpg
curl -o bandar-seri-begawan-brunei.jpg https://nomadlist.com/assets/cities/500px/bandar-seri-begawan-brunei.jpg
curl -o antwerp-belgium.jpg https://nomadlist.com/assets/cities/500px/antwerp-belgium.jpg
curl -o san-juan-pr-united-states.jpg https://nomadlist.com/assets/cities/500px/san-juan-pr-united-states.jpg
curl -o jeddah-saudi-arabia.jpg https://nomadlist.com/assets/cities/500px/jeddah-saudi-arabia.jpg
curl -o tokyo-japan.jpg https://nomadlist.com/assets/cities/500px/tokyo-japan.jpg
curl -o munich-germany.jpg https://nomadlist.com/assets/cities/500px/munich-germany.jpg
curl -o alexandria-egypt.jpg https://nomadlist.com/assets/cities/500px/alexandria-egypt.jpg
curl -o barcelona-spain.jpg https://nomadlist.com/assets/cities/500px/barcelona-spain.jpg
curl -o manama-bahrain.jpg https://nomadlist.com/assets/cities/500px/manama-bahrain.jpg
curl -o dunedin-new-zealand.jpg https://nomadlist.com/assets/cities/500px/dunedin-new-zealand.jpg
curl -o como-italy.jpg https://nomadlist.com/assets/cities/500px/como-italy.jpg
curl -o playa-del-carmen-mexico.jpg https://nomadlist.com/assets/cities/500px/playa-del-carmen-mexico.jpg
curl -o islamabad-pakistan.jpg https://nomadlist.com/assets/cities/500px/islamabad-pakistan.jpg
curl -o wellington-new-zealand.jpg https://nomadlist.com/assets/cities/500px/wellington-new-zealand.jpg
curl -o bellingham-wa-united-states.jpg https://nomadlist.com/assets/cities/500px/bellingham-wa-united-states.jpg
curl -o bern-switzerland.jpg https://nomadlist.com/assets/cities/500px/bern-switzerland.jpg
curl -o nice-france.jpg https://nomadlist.com/assets/cities/500px/nice-france.jpg
curl -o denver-co-united-states.jpg https://nomadlist.com/assets/cities/500px/denver-co-united-states.jpg
curl -o vancouver-canada.jpg https://nomadlist.com/assets/cities/500px/vancouver-canada.jpg
curl -o lodz-poland.jpg https://nomadlist.com/assets/cities/500px/lodz-poland.jpg
curl -o budva-montenegro.jpg https://nomadlist.com/assets/cities/500px/budva-montenegro.jpg
curl -o kitchener-canada.jpg https://nomadlist.com/assets/cities/500px/kitchener-canada.jpg
curl -o turku-finland.jpg https://nomadlist.com/assets/cities/500px/turku-finland.jpg
curl -o male-maldives.jpg https://nomadlist.com/assets/cities/500px/male-maldives.jpg
curl -o kochi-india.jpg https://nomadlist.com/assets/cities/500px/kochi-india.jpg
curl -o milwaukee-wi-united-states.jpg https://nomadlist.com/assets/cities/500px/milwaukee-wi-united-states.jpg
curl -o boulder-co-united-states.jpg https://nomadlist.com/assets/cities/500px/boulder-co-united-states.jpg
curl -o trondheim-norway.jpg https://nomadlist.com/assets/cities/500px/trondheim-norway.jpg
curl -o burgas-bulgaria.jpg https://nomadlist.com/assets/cities/500px/burgas-bulgaria.jpg
curl -o seattle-wa-united-states.jpg https://nomadlist.com/assets/cities/500px/seattle-wa-united-states.jpg
curl -o salzburg-austria.jpg https://nomadlist.com/assets/cities/500px/salzburg-austria.jpg
curl -o dhaka-bangladesh.jpg https://nomadlist.com/assets/cities/500px/dhaka-bangladesh.jpg
curl -o aachen-germany.jpg https://nomadlist.com/assets/cities/500px/aachen-germany.jpg
curl -o hannover-germany.jpg https://nomadlist.com/assets/cities/500px/hannover-germany.jpg
curl -o auckland-new-zealand.jpg https://nomadlist.com/assets/cities/500px/auckland-new-zealand.jpg
curl -o leeds-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/leeds-united-kingdom.jpg
curl -o shanghai-china.jpg https://nomadlist.com/assets/cities/500px/shanghai-china.jpg
curl -o modena-italy.jpg https://nomadlist.com/assets/cities/500px/modena-italy.jpg
curl -o columbus-oh-united-states.jpg https://nomadlist.com/assets/cities/500px/columbus-oh-united-states.jpg
curl -o honolulu-hawaii.jpg https://nomadlist.com/assets/cities/500px/honolulu-hawaii.jpg
curl -o san-pedro-belize.jpg https://nomadlist.com/assets/cities/500px/san-pedro-belize.jpg
curl -o yekaterinburg-russia.jpg https://nomadlist.com/assets/cities/500px/yekaterinburg-russia.jpg
curl -o los-angeles-ca-united-states.jpg https://nomadlist.com/assets/cities/500px/los-angeles-ca-united-states.jpg
curl -o omaha-ne-united-states.jpg https://nomadlist.com/assets/cities/500px/omaha-ne-united-states.jpg
curl -o tomsk-russia.jpg https://nomadlist.com/assets/cities/500px/tomsk-russia.jpg
curl -o minneapolis-mn-united-states.jpg https://nomadlist.com/assets/cities/500px/minneapolis-mn-united-states.jpg
curl -o christchurch-new-zealand.jpg https://nomadlist.com/assets/cities/500px/christchurch-new-zealand.jpg
curl -o ahmedabad-india.jpg https://nomadlist.com/assets/cities/500px/ahmedabad-india.jpg
curl -o hong-kong-hong-kong.jpg https://nomadlist.com/assets/cities/500px/hong-kong-hong-kong.jpg
curl -o makati-philippines.jpg https://nomadlist.com/assets/cities/500px/makati-philippines.jpg
curl -o novosibirsk-russia.jpg https://nomadlist.com/assets/cities/500px/novosibirsk-russia.jpg
curl -o kosice-slovakia.jpg https://nomadlist.com/assets/cities/500px/kosice-slovakia.jpg
curl -o bergen-norway.jpg https://nomadlist.com/assets/cities/500px/bergen-norway.jpg
curl -o cork-ireland.jpg https://nomadlist.com/assets/cities/500px/cork-ireland.jpg
curl -o grodno-belarus.jpg https://nomadlist.com/assets/cities/500px/grodno-belarus.jpg
curl -o beirut-lebanon.jpg https://nomadlist.com/assets/cities/500px/beirut-lebanon.jpg
curl -o johannesburg-south-africa.jpg https://nomadlist.com/assets/cities/500px/johannesburg-south-africa.jpg
curl -o dusseldorf-germany.jpg https://nomadlist.com/assets/cities/500px/dusseldorf-germany.jpg
curl -o nanaimo-canada.jpg https://nomadlist.com/assets/cities/500px/nanaimo-canada.jpg
curl -o malmo-sweden.jpg https://nomadlist.com/assets/cities/500px/malmo-sweden.jpg
curl -o rotterdam-netherlands.jpg https://nomadlist.com/assets/cities/500px/rotterdam-netherlands.jpg
curl -o warsaw-poland.jpg https://nomadlist.com/assets/cities/500px/warsaw-poland.jpg
curl -o cape-town-south-africa.jpg https://nomadlist.com/assets/cities/500px/cape-town-south-africa.jpg
curl -o santa-monica-ca-united-states.jpg https://nomadlist.com/assets/cities/500px/santa-monica-ca-united-states.jpg
curl -o stockholm-sweden.jpg https://nomadlist.com/assets/cities/500px/stockholm-sweden.jpg
curl -o bloomington-in-united-states.jpg https://nomadlist.com/assets/cities/500px/bloomington-in-united-states.jpg
curl -o kaliningrad-russia.jpg https://nomadlist.com/assets/cities/500px/kaliningrad-russia.jpg
curl -o amsterdam-netherlands.jpg https://nomadlist.com/assets/cities/500px/amsterdam-netherlands.jpg
curl -o lethbridge-canada.jpg https://nomadlist.com/assets/cities/500px/lethbridge-canada.jpg
curl -o copenhagen-denmark.jpg https://nomadlist.com/assets/cities/500px/copenhagen-denmark.jpg
curl -o kolkata-india.jpg https://nomadlist.com/assets/cities/500px/kolkata-india.jpg
curl -o graz-austria.jpg https://nomadlist.com/assets/cities/500px/graz-austria.jpg
curl -o dubai-united-arab-emirates.jpg https://nomadlist.com/assets/cities/500px/dubai-united-arab-emirates.jpg
curl -o samara-russia.jpg https://nomadlist.com/assets/cities/500px/samara-russia.jpg
curl -o lyon-france.jpg https://nomadlist.com/assets/cities/500px/lyon-france.jpg
curl -o karachi-pakistan.jpg https://nomadlist.com/assets/cities/500px/karachi-pakistan.jpg
curl -o alicante-spain.jpg https://nomadlist.com/assets/cities/500px/alicante-spain.jpg
curl -o rio-de-janeiro-brazil.jpg https://nomadlist.com/assets/cities/500px/rio-de-janeiro-brazil.jpg
curl -o calgary-canada.jpg https://nomadlist.com/assets/cities/500px/calgary-canada.jpg
curl -o portland-or-united-states.jpg https://nomadlist.com/assets/cities/500px/portland-or-united-states.jpg
curl -o anchorage-ak-united-states.jpg https://nomadlist.com/assets/cities/500px/anchorage-ak-united-states.jpg
curl -o dalian-china.jpg https://nomadlist.com/assets/cities/500px/dalian-china.jpg
curl -o eindhoven-netherlands.jpg https://nomadlist.com/assets/cities/500px/eindhoven-netherlands.jpg
curl -o gothenburg-sweden.jpg https://nomadlist.com/assets/cities/500px/gothenburg-sweden.jpg
curl -o jyvaskyla-finland.jpg https://nomadlist.com/assets/cities/500px/jyvaskyla-finland.jpg
curl -o port-said-egypt.jpg https://nomadlist.com/assets/cities/500px/port-said-egypt.jpg
curl -o tromso-norway.jpg https://nomadlist.com/assets/cities/500px/tromso-norway.jpg
curl -o wroclaw-poland.jpg https://nomadlist.com/assets/cities/500px/wroclaw-poland.jpg
curl -o beijing-china.jpg https://nomadlist.com/assets/cities/500px/beijing-china.jpg
curl -o nizhny-russia.jpg https://nomadlist.com/assets/cities/500px/nizhny-russia.jpg
curl -o bordeaux-france.jpg https://nomadlist.com/assets/cities/500px/bordeaux-france.jpg
curl -o bournemouth-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/bournemouth-united-kingdom.jpg
curl -o el-jadida-morocco.jpg https://nomadlist.com/assets/cities/500px/el-jadida-morocco.jpg
curl -o naples-italy.jpg https://nomadlist.com/assets/cities/500px/naples-italy.jpg
curl -o dar-es-salaam-tanzania.jpg https://nomadlist.com/assets/cities/500px/dar-es-salaam-tanzania.jpg
curl -o tel-aviv-israel.jpg https://nomadlist.com/assets/cities/500px/tel-aviv-israel.jpg
curl -o park-city-ut-united-states.jpg https://nomadlist.com/assets/cities/500px/park-city-ut-united-states.jpg
curl -o cardiff-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/cardiff-united-kingdom.jpg
curl -o lugano-switzerland.jpg https://nomadlist.com/assets/cities/500px/lugano-switzerland.jpg
curl -o reykjavik-iceland.jpg https://nomadlist.com/assets/cities/500px/reykjavik-iceland.jpg
curl -o glasgow-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/glasgow-united-kingdom.jpg
curl -o limassol-cyprus.jpg https://nomadlist.com/assets/cities/500px/limassol-cyprus.jpg
curl -o grenoble-france.jpg https://nomadlist.com/assets/cities/500px/grenoble-france.jpg
curl -o leiden-netherlands.jpg https://nomadlist.com/assets/cities/500px/leiden-netherlands.jpg
curl -o tripoli-libya.jpg https://nomadlist.com/assets/cities/500px/tripoli-libya.jpg
curl -o dublin-ireland.jpg https://nomadlist.com/assets/cities/500px/dublin-ireland.jpg
curl -o basel-switzerland.jpg https://nomadlist.com/assets/cities/500px/basel-switzerland.jpg
curl -o nicosia-cyprus.jpg https://nomadlist.com/assets/cities/500px/nicosia-cyprus.jpg
curl -o gibraltar-gibraltar.jpg https://nomadlist.com/assets/cities/500px/gibraltar-gibraltar.jpg
curl -o kazan-russia.jpg https://nomadlist.com/assets/cities/500px/kazan-russia.jpg
curl -o chania-greece.jpg https://nomadlist.com/assets/cities/500px/chania-greece.jpg
curl -o ciutadella-spain.jpg https://nomadlist.com/assets/cities/500px/ciutadella-spain.jpg
curl -o brisbane-australia.jpg https://nomadlist.com/assets/cities/500px/brisbane-australia.jpg
curl -o gurgaon-india.jpg https://nomadlist.com/assets/cities/500px/gurgaon-india.jpg
curl -o gold-coast-australia.jpg https://nomadlist.com/assets/cities/500px/gold-coast-australia.jpg
curl -o birmingham-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/birmingham-united-kingdom.jpg
curl -o bristol-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/bristol-united-kingdom.jpg
curl -o canberra-australia.jpg https://nomadlist.com/assets/cities/500px/canberra-australia.jpg
curl -o sliema-malta.jpg https://nomadlist.com/assets/cities/500px/sliema-malta.jpg
curl -o kelowna-canada.jpg https://nomadlist.com/assets/cities/500px/kelowna-canada.jpg
curl -o washington-dc-united-states.jpg https://nomadlist.com/assets/cities/500px/washington-dc-united-states.jpg
curl -o galway-ireland.jpg https://nomadlist.com/assets/cities/500px/galway-ireland.jpg
curl -o oslo-norway.jpg https://nomadlist.com/assets/cities/500px/oslo-norway.jpg
curl -o london-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/london-united-kingdom.jpg
curl -o vladivostok-russia.jpg https://nomadlist.com/assets/cities/500px/vladivostok-russia.jpg
curl -o cambridge-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/cambridge-united-kingdom.jpg
curl -o port-moresby-papua-new-guinea.jpg https://nomadlist.com/assets/cities/500px/port-moresby-papua-new-guinea.jpg
curl -o moscow-russia.jpg https://nomadlist.com/assets/cities/500px/moscow-russia.jpg
curl -o baku-azerbaijan.jpg https://nomadlist.com/assets/cities/500px/baku-azerbaijan.jpg
curl -o brussels-belgium.jpg https://nomadlist.com/assets/cities/500px/brussels-belgium.jpg
curl -o philadelphia-pa-united-states.jpg https://nomadlist.com/assets/cities/500px/philadelphia-pa-united-states.jpg
curl -o la-paz-bolivia.jpg https://nomadlist.com/assets/cities/500px/la-paz-bolivia.jpg
curl -o haifa-israel.jpg https://nomadlist.com/assets/cities/500px/haifa-israel.jpg
curl -o chicago-il-united-states.jpg https://nomadlist.com/assets/cities/500px/chicago-il-united-states.jpg
curl -o venice-italy.jpg https://nomadlist.com/assets/cities/500px/venice-italy.jpg
curl -o izhevsk-russia.jpg https://nomadlist.com/assets/cities/500px/izhevsk-russia.jpg
curl -o macau-macau.jpg https://nomadlist.com/assets/cities/500px/macau-macau.jpg
curl -o milan-italy.jpg https://nomadlist.com/assets/cities/500px/milan-italy.jpg
curl -o chandigarh-india.jpg https://nomadlist.com/assets/cities/500px/chandigarh-india.jpg
curl -o darwin-australia.jpg https://nomadlist.com/assets/cities/500px/darwin-australia.jpg
curl -o hamilton-bermuda.jpg https://nomadlist.com/assets/cities/500px/hamilton-bermuda.jpg
curl -o turin-italy.jpg https://nomadlist.com/assets/cities/500px/turin-italy.jpg
curl -o melbourne-australia.jpg https://nomadlist.com/assets/cities/500px/melbourne-australia.jpg
curl -o leicester-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/leicester-united-kingdom.jpg
curl -o edinburgh-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/edinburgh-united-kingdom.jpg
curl -o kinosaki-onsen-japan.jpg https://nomadlist.com/assets/cities/500px/kinosaki-onsen-japan.jpg
curl -o rome-italy.jpg https://nomadlist.com/assets/cities/500px/rome-italy.jpg
curl -o paris-france.jpg https://nomadlist.com/assets/cities/500px/paris-france.jpg
curl -o san-francisco-ca-united-states.jpg https://nomadlist.com/assets/cities/500px/san-francisco-ca-united-states.jpg
curl -o boston-ma-united-states.jpg https://nomadlist.com/assets/cities/500px/boston-ma-united-states.jpg
curl -o coventry-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/coventry-united-kingdom.jpg
curl -o manchester-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/manchester-united-kingdom.jpg
curl -o saint-helier-jersey.jpg https://nomadlist.com/assets/cities/500px/saint-helier-jersey.jpg
curl -o helsinki-finland.jpg https://nomadlist.com/assets/cities/500px/helsinki-finland.jpg
curl -o kaunas-lithuania.jpg https://nomadlist.com/assets/cities/500px/kaunas-lithuania.jpg
curl -o mar-del-plata-argentina.jpg https://nomadlist.com/assets/cities/500px/mar-del-plata-argentina.jpg
curl -o geneva-switzerland.jpg https://nomadlist.com/assets/cities/500px/geneva-switzerland.jpg
curl -o antalya-turkey.jpg https://nomadlist.com/assets/cities/500px/antalya-turkey.jpg
curl -o salt-lake-city-ut-united-states.jpg https://nomadlist.com/assets/cities/500px/salt-lake-city-ut-united-states.jpg
curl -o paphos-cyprus.jpg https://nomadlist.com/assets/cities/500px/paphos-cyprus.jpg
curl -o lausanne-switzerland.jpg https://nomadlist.com/assets/cities/500px/lausanne-switzerland.jpg
curl -o new-york-city-ny-united-states.jpg https://nomadlist.com/assets/cities/500px/new-york-city-ny-united-states.jpg
curl -o jerusalem-israel.jpg https://nomadlist.com/assets/cities/500px/jerusalem-israel.jpg
curl -o izmir-turkey.jpg https://nomadlist.com/assets/cities/500px/izmir-turkey.jpg
curl -o zurich-switzerland.jpg https://nomadlist.com/assets/cities/500px/zurich-switzerland.jpg
curl -o bodrum-turkey.jpg https://nomadlist.com/assets/cities/500px/bodrum-turkey.jpg
curl -o istanbul-turkey.jpg https://nomadlist.com/assets/cities/500px/istanbul-turkey.jpg
curl -o ankara-turkey.jpg https://nomadlist.com/assets/cities/500px/ankara-turkey.jpg
curl -o luanda-angola.jpg https://nomadlist.com/assets/cities/500px/luanda-angola.jpg
curl -o aberdeen-united-kingdom.jpg https://nomadlist.com/assets/cities/500px/aberdeen-united-kingdom.jpg
curl -o harare-zimbabwe.jpg https://nomadlist.com/assets/cities/500px/harare-zimbabwe.jpg
curl -o cairns-australia.jpg https://nomadlist.com/assets/cities/500px/cairns-australia.jpg
curl -o accra-ghana.jpg https://nomadlist.com/assets/cities/500px/accra-ghana.jpg
curl -o krasnoyarsk-russia.jpg https://nomadlist.com/assets/cities/500px/krasnoyarsk-russia.jpg
curl -o cydonia-mars.jpg https://nomadlist.com/assets/cities/500px/cydonia-mars.jpg