curl -o chiang-mai-thailand.jpg https://nomadlist.com/assets/cities/500px/chiang-mai-thailand.jpg
curl -o varna-bulgaria.jpg https://nomadlist.com/assets/cities/500px/varna-bulgaria.jpg
curl -o novi-sad-serbia.jpg https://nomadlist.com/assets/cities/500px/novi-sad-serbia.jpg
curl -o belgrade-serbia.jpg https://nomadlist.com/assets/cities/500px/belgrade-serbia.jpg
curl -o braga-portugal.jpg https://nomadlist.com/assets/cities/500px/braga-portugal.jpg
curl -o bangkok-thailand.jpg https://nomadlist.com/assets/cities/500px/bangkok-thailand.jpg
curl -o odesa-ukraine.jpg https://nomadlist.com/assets/cities/500px/odesa-ukraine.jpg
curl -o tbilisi-georgia.jpg https://nomadlist.com/assets/cities/500px/tbilisi-georgia.jpg
curl -o kota-kinabalu-malaysia.jpg https://nomadlist.com/assets/cities/500px/kota-kinabalu-malaysia.jpg
curl -o kingston-jamaica.jpg https://nomadlist.com/assets/cities/500px/kingston-jamaica.jpg
curl -o tijuana-mexico.jpg https://nomadlist.com/assets/cities/500px/tijuana-mexico.jpg
curl -o osijek-croatia.jpg https://nomadlist.com/assets/cities/500px/osijek-croatia.jpg
curl -o budapest-hungary.jpg https://nomadlist.com/assets/cities/500px/budapest-hungary.jpg
curl -o taichung-taiwan.jpg https://nomadlist.com/assets/cities/500px/taichung-taiwan.jpg
curl -o addis-ababa-ethiopia.jpg https://nomadlist.com/assets/cities/500px/addis-ababa-ethiopia.jpg
curl -o navi-mumbai-india.jpg https://nomadlist.com/assets/cities/500px/navi-mumbai-india.jpg
curl -o lviv-ukraine.jpg https://nomadlist.com/assets/cities/500px/lviv-ukraine.jpg
curl -o taghazout-morocco.jpg https://nomadlist.com/assets/cities/500px/taghazout-morocco.jpg
curl -o las-vegas-nv-united-states.jpg https://nomadlist.com/assets/cities/500px/las-vegas-nv-united-states.jpg
curl -o split-croatia.jpg https://nomadlist.com/assets/cities/500px/split-croatia.jpg
curl -o sofia-bulgaria.jpg https://nomadlist.com/assets/cities/500px/sofia-bulgaria.jpg
curl -o chattanooga-tn-united-states.jpg https://nomadlist.com/assets/cities/500px/chattanooga-tn-united-states.jpg
curl -o porto-portugal.jpg https://nomadlist.com/assets/cities/500px/porto-portugal.jpg
curl -o kampala-uganda.jpg https://nomadlist.com/assets/cities/500px/kampala-uganda.jpg